### ISSUE TITLE
Toggle function on plots of results

### ISSUE THREAD

**Issue by nnoll** [neherlab/covid19_scenarios#132]
# 🙋 Feature Request

Our previous plotting library Plotly.js had the ability to click on a legend label to toggle whether or not a particular plot is displayed. I've searched but can't find a way to recapitulate this feature with our current plotting library. 

This would have two major benefits:
  (i) We could show data not shown here (or shown previously) e.g. predicted hospitalizations.
  (ii) We could analyze particular results in detail and linear scaling of data would be more useful.

## 🤔 Expected Behavior

We should be able to determine what results from the simulation is plotted dynamically.

## 😯 Current Behavior

It does not toggle. Whatever plots we decide to show are shown.

## 💁 Possible Solution

Going back to Plotly is subobtimal as it was a rather slow library. 
If we can't find a way to make this work in the context of the current library, is there a solution that utilizes our current form inputs?

## 🔦 Context

It would be good for fine tuning your simulation parameters by fitting to empirical hospitalization data and then removing the plot when not needed.

**Comment by rcbevans** [comment]
Created a PR adding the desired functionality.  By default, all data available is shown on the chart.  Cursor now shows the 'hand' on hover to indicate interactivity.  Clicking toggles visibility of line/scatter on chart, and when disabled, the legend label shows with dark-grey, rather than black, text, and with strike-through.

![Screenshot of feature implementation](https://user-images.githubusercontent.com/2041260/77282297-c41eed00-6c86-11ea-9c6c-99cf1b093c9e.png)
