### ISSUE TITLE
Inflated ICU numbers

### ISSUE THREAD

**Issue by jc92** [neherlab/covid19_scenarios#172]
# 🐛 Bug Report

## How to reproduce

Steps to reproduce the issue:

 1. Open the application in a browser

 2. Run scenario for any country, e.g. Switzerland

 3. Export and compare hospitalised vs critical+overflow (ICU)

## 😯 Current Behavior
The numbers for critical+overflow are almost as high as for hospitalised.

## 🤔 Expected Behavior
The numbers for critical+overflow ( = ICU) should be a fraction of hospitalised.

## 🔦 Context
Related discussion on spectrum:
https://spectrum.chat/covid19-scenarios/general/questions-discussions~8d49f461-a890-4beb-84f7-2d6ed0ae503a?m=MTU4NDk5MzA0ODY2Mg==

https://spectrum.chat/covid19-scenarios/general/questions-discussions~8d49f461-a890-4beb-84f7-2d6ed0ae503a?m=MTU4NDk5NzQ4MTg4MA==

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          | Google Chrome
| Operating System | MacOS
|                  |

**Comment by nnoll** [comment]
I'm not convinced this is a bug. For simplicity, let's just focus on a reduced/simplified set of ODE's of the hospital/ICU interaction. And let's temporarily forget about the overflow class

Let A be the constant rate of patients sent to the hospital. 
Let a be the rate patients become critical and must go to the ICU.
Let b be the rate of recovery in the hospital
Let d be the rate of recovery in the ICU that goes back to the hospital

The ODEs under this assumption.

dH/dt = A + d C- (a+b) H
dC/dt = aH - d C

Let's focus on steady state: C_* = (a/d) H_*. Since we assume the rate that people leave the ICU is *slower* than the rate they enter (14 day vs 3 day), then a/d > 1. So this system of equations would have more people in critical care than in the hospital at equilibrium. You can test this by playing with the ratio of these values.

**Comment by jc92** [comment]
Apologies if my questions are basic, it's been a while since I solved my last ODE.
Does your assumption imply that hospitalised people also include ICU patients?

**Comment by nnoll** [comment]
This was pointed out to me by @rneher that the confusion could be caused by our loose terminology. The hospitalized category includes people in the hospital but not ICU/ICU overflow. We will change the terms to severe to be more accurate.

**Comment by jc92** [comment]
Thanks for the example. 
Just wondering if hospitalized category includes people in the hospital but not ICU/ICU overflow, why do we have dH/dt depending on dC ?

**Comment by nnoll** [comment]
No worries! I'm sorry if I am being confusion. We've hit the limitation of math notation without latex. 

dC/dt denotes the time derivative of C. Read it as a singular variable. d*C is the rate at which critical patients leave the ICU and re-enter the hospital. In a given time step, the number of hospital patients increases by the constant rate A, but also the number of critical patients re-entering the hospital which is why it shows up there.

**Comment by jc92** [comment]
Thanks!
Just out of completeness. I am assuming you also take into account the fatality rate in dC/dt in the real model as well. Is this fatality rate within the window of 14 days?
Given that it is between 30-50% for critical cases.  I am just struggling to see how the number of ICU patients can remain as high as hospitalized ones.

**Comment by nnoll** [comment]
Yes fatality is included in the full model.

I think another way to think about this is that we, based on estimates provided by our clinical colleagues, we assume patients reside in the ICU ~3x longer than they do in the hospital, independent of their final outcomes, which causes patients to accumulate in the ICU. I think the way to see this experimentally is set the ICU residence time equal to the hospital residence time to ICU residence time and see the results.

**Comment by jc92** [comment]
Indeed, I played around with different length of stays. Indeed the split ICU vs hospital looks different.
Another test I did, was setting fatality rate to 100%, then the peaks for hospitalised and ICU for CH /w moderate are fairly similar (~12% difference)
Does the fatality % happened at the end of the 14 days or randomly across the 2 weeks in ICU.

Thanks again, for all your explanations. Scary to think in moderate mitigation scenario a prediction of 16x time the national ICU bed number is possible.

**Comment by nnoll** [comment]
The rates are set up such that the average time someone spends in an ICU, independent of the outcome, will be 14 days always. Playing with the individual fractions plays with the ratio of the rates of the 2 possible outcomes, recovery vs mortality, keeping the total rate fixed. No stochastic process is simulated as of now, but we are showing the average of what would be an poisson process with the average residence time set to 14 days. Thus it would happen randomly across the 14 days with the fixed average. Hope this helps.

**Comment by jc92** [comment]
" independent of the outcome, will be 14 days always" does that mean a deceased person is still considered in the ICU up to 2 weeks?

**Comment by nnoll** [comment]
No, they will be removed whenever the transition to a new state. I was reporting the mean time, independent of final outcome. I'll close this issue in the interest of housekeeping, but I urge you to ping me on Spectrum to continue the discussion :)
