### ISSUE TITLE
Inconsistent death count depending on simulation range

### ISSUE THREAD

**Issue by nielsenko** [neherlab/covid19_scenarios#187]
I tried to run a simulation for Denmark with default data, first with the default simulation range, ie. until september 1st, and then one until January 1st 2021.

Checking the death count on the 31st of august in both runs, come up with widely different numbers, ie. 346 vs. 489.

Did the same for USA-New York and got: 7281 vs. 10245.

I suspect you suffer from significant numeric instability.

**Comment by nnoll** [comment]
@nielsenko I suspect this is due to the reinterpolation of the mitigation plot onto the new time window and not due to numerical instability within the simulation. 

To test this, I ran Denmark twice with all default parameters, but with no mitigation, once for the default time window and once until January 1st 2021. Both times the number of deaths on August 31st was 66452. 

Thus we most likely need a more robust way of changing the mitigation curve when the time window updates.

**Comment by nielsenko** [comment]
Good to hear you already have an hypothesis as to the cause. Good luck with your efforts.

**Comment by albin-attentec** [comment]
I havs seen similar effects on the data-set for sweden, but only if i do one simulation after the other without reloading.
I belive this supports your theory @nnoll

**Comment by nielsenko** [comment]
I have tried the preview (https://covid19-scenarios-git-fix-interpolation.covid19-scenarios.now.sh). It is much better but still not perfect.

Fx, running default parameters with CHE-Basel-Stadt, and then extending simulation time range until 1st of January 2021, gives a difference in accumulated deaths on the 31st of August of 1760 vs 1775.

**Comment by nnoll** [comment]
@nielsenko I think with the current method that the mitigation is input by the user - i.e. discrete points that have to be re-interpolated onto a different time-window upon update - this is the best accuracy we will be able to achieve, especially when it directly modifies an exponential growth rate.

When Issue #14 is finally implemented the remainder of this problem will resolve as we won't have to guess at what to set values to upon time range updates. As this whole mitigation widget is being re-imagined near-term, we probably won't fix this small deviation in it's current form. Hope this helps!
