### ISSUE TITLE
Reduce bundle size

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#23]
Current bundle size is huge, ~10 MBytes before gzip

 - investigate Home.js bundle size
 - trim and tree-shake libraries
 - add more code splitting
 
The bundle analyzer can be run with `yarn alalyze` or `yarn alalyze:watch`.

**Comment by jsmith** [comment]
Hey @ivan-aksamentov I saw the `help-wanted` label and thought I would take a look. To start, I just decided to look for unused dependencies and actually found several (or in the case of `mathjs`, minimally used). The total size of these packages is ~`4.2MB` before being gzipped. I realize that sometimes dependencies will seem unused and I tried my best to to avoid these packages. I created a [branch on a fork](https://github.com/neherlab/covid19_scenarios/compare/master...jsmith:polish/dependencies) with these changes.

Here is the list:
- `plotly.js` as it is unused (`3.2MB`)
- `react-plotly.js` as it is unused (`7.6kB`)
- `mathjs` as the builtin [Math library](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math) can be instead since only the `pi` variable and `round` are being used from `mathjs` (`632.4kB`).
- `jquery` as it is unused (`86kB`)
- `popper.js` as it is unused (`20.7kB`)
- `react-popper` as it it unused (`37.3kB`)
- `react-with-direction` as it is unused (`56.2kB`)
- `react-with-styles` as it is unused (`16.6kB`)
- `react-with-styles-interface-css` as it is unused (`50.3kB`)
- `redux-saga-test-plan` as it is unused (`79.4kB`)
- `redux-thunk` as it is unused (`352B`)
- `seamless-immutable` as it is unused (`7.5kB`)

The following type packages were also removed from the dev dependencies:
- `@types/plotly.js `
- `@types/react-plotly.js`

Not that other than removing the type files of packages removed from the dependencies, I did not look at the dev dependencies although I'm sure many could potentially be removed to speed up development maybe?

**Comment by ivan-aksamentov** [comment]
@jsmith Hi Jacob, 

Thanks so much for the detailed report!

Yep, most of them are no longer used. I think some of these might be the peer deps.

I would definitely keep `redux-saga-test-plan` for testing sagas, that will be hopefully coming  soon(ish). 

Have you noticed any improvements in bundle size (`yarn analyze`)?
If this builds and works (`yarn dev`, `yarn prod`), feel free to submit a PR! 

Let me know if you have other ideas on how to improve our mess. :)

**Comment by jsmith** [comment]
Running `yarn analyze` I see that the total stat size is `6.62MB`, parsed size is `2.07` MB and gzipped is `494.9KB`. I've also added back `redux-saga-test-plan`, confirmed that both `yarn dev`/`yarn prod` work and created a PR :) (See #46) I will definitely let you know if I have any other ideas!

**Comment by jsmith** [comment]
Also just to note, I'm fairly confident none of my changes triggered any peer deps warnings. I was trying to look out for that!

**Comment by ivan-aksamentov** [comment]
I think we are doing a bit better. We will probably do another pass in a couple of weeks.
Closing the issue.
