### ISSUE TITLE
yarn install ERROR - no such file or directory

### ISSUE THREAD

**Issue by MikaMaracuja** [neherlab/covid19_scenarios#265]
# 📚 Documentation
I have followed the installation routine and had a yarn version (1 < version <  2), but this did not work for me. 

This got the installation running finally:
sudo apt remove cmdtest
sudo apt remove yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update  
sudo apt-get install yarn

My error message was:
> yarn install
ERROR: [Errno 2] No such file or directory: 'install'

## Related
https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install

Cheers,
Michael

**Comment by ivan-aksamentov** [comment]
@MikaMaracuja  you should never install node or yarn through apt or other OS package manager in the first place, because:

 - they are always obsolete there
 - global package installation requires root, because node is installed into a system directory
 - installing multiple versions is impossible

We recommend using [nvm](https://github.com/nvm-sh/nvm) instead.
