### ISSUE TITLE
Custom age distributions

### ISSUE THREAD

**Issue by rneher** [neherlab/covid19_scenarios#332]
## 🙋 Feature Request
We have had multiple requests for adjusting age distributions when local community doesn't match the country.

## 🔦 Context
Since severity is heavily age dependent, the burden on the health care system depends strongly on the age distribution of the population. 

## 💁 Possible Solution
Add a column to the severity table that is prepopulated with values of the country from a scenario but can be modified. 

- [x] add a column to the severity table
- [x] once modified, the value of the age distribution drop down should go to custom
- [x] currently, `state` contains a key for the age distribution which is read out in the `runSimulation` function. This should probably be replaced by the distribution proper (an array of 9 numbers)  
- [x] the URL should contain the values of the age distributions, rather than the country key
- [x] update the description of the severity card to reflect these changes.

**Comment by gj262** [comment]
Hi @rneher in the project page for this issue the column is described as having numbers 0-100. However the data passed to run() are population counts per age segment. I would guess that you don't want the app to do that level of rounding. So. Should this column be raw numbers?

The column could have a total below it to help the user balance the numbers e.g. 
Your Total = 376000123
Country Population = 37600000

If the user chooses a province/state/county the column values could be extrapolated from the province/state/county population versus the country population to give them a saner starting point.

**Comment by gj262** [comment]
I've created a branch and added the column to the table there. 
feat/custom-age-distribution.

**Comment by gj262** [comment]
FYI, I'm working some more on this today.

**Comment by gj262** [comment]
I think rather than modify the state.population.country value, and have that show up in the form field, it might be better to indicate visually that the age distribution has changed from defaults. Like:

![Screen Shot 2020-04-02 at 9 49 08 AM](https://user-images.githubusercontent.com/6854428/78276452-e7883a00-74c7-11ea-831e-c0c55291382e.png)

The * could be red and hoverable with "The age distribution for this scenario has been modified from the country defaults". A bonus feature would include a side by side comparison of the values in the info.

**Comment by nnoll** [comment]
I worry about the asterisk, just because in principle you could modify the numbers to be substantially different from the initial condition, in which case the pointer is relatively meaningless. Personally I would vote for a simple change to "Custom" as a catch all state once you start fiddling with the numbers.

**Comment by nnoll** [comment]
I would also vote for going with the basic numbers for the population, otherwise we'll need to impose a constraint on the column sum which seems inconvienent for users. For those who want to enter as fractions, the option still exists since this will be scaled by populationServed anyways.

**Comment by nnoll** [comment]
Longer term, it would make sense to allow users to import their "custom" scenarios with nice names but this is a seperate, longer term issue.

**Comment by gj262** [comment]
> I would also vote for going with the basic numbers for the population, otherwise we'll need to impose a constraint on the column sum which seems inconvienent for users. For those who want to enter as fractions, the option still exists since this will be scaled by populationServed anyways.

Just so I'm clear, 'basic numbers' means the values from country_age_distribution.json right?

**Comment by nnoll** [comment]
Yeah sorry for the confusion. I mean I think it's easier to inputs counts (# of people) then fractions -- exactly what you are doing.

**Comment by gj262** [comment]
> Longer term, it would make sense to allow users to import their "custom" scenarios with nice names but this is a seperate, longer term issue.

I've been tinkering with that in #293 but that is very much a work in progress.
