### ISSUE TITLE
Improve styling and content of the landing page

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#384]
# 🙋 Feature Request

This ^.
Basically Landing page is empty and not at all like the rest of the app. We need some artistic touch there. Bring some life into it. :)

## 🔦 Context

Importance: will be included into the new release / announcement of the new domain

## 😯 Describe the feature

All optional, non-exhastive (use your imagination!):
 - [ ] SVG should be embedded into the page, right now it loads with a delay on slow connections
 - [ ] Bigger "skip" checkbox, closer to the button. Most users want it checked.
 - [ ] Checkbox should not disappear on the next page load if checked.
 - [ ] Color- and shape-wise should look more like the simulator itself
 - [ ] We might want the navbar on landing page too
 - [ ] Round button looks very differently from our square buttons
 - [ ] Much larger image, updated for the current looks
 - [ ] Maybe loop-roll screencast .mp4 instead of the image  (for fast network && desktop)?
 - [ ] Maybe a youtube video with @rneher explaining the app (does not exist yet)
 - [ ] More meaningful text on the page (from readme?)
 - [ ] Nice-looking links to the Lab page, Github and Richard's Twitter
 - [ ] Maybe add links to FAQ and about?
 - [ ] Maybe team from readme?

## Related

 - https://github.com/neherlab/covid19_scenarios/issues/107
 - https://github.com/neherlab/covid19_scenarios/pull/163

**Comment by realdy** [comment]
Hello, I looked at this project and was really interested in helping out during this time.

How does this look for a prelim image?
![PrelimImage](https://user-images.githubusercontent.com/45107348/78416627-1271ab80-75f8-11ea-80c2-4e6f29b32e72.png)

**Comment by ivan-aksamentov** [comment]
@realdy I was hoping for more (not less) colors and larger image/video - 1/4 of screen or so.
Maybe we don't need the wave. Button should be bigger - this button is the only reason our app exist.

These all are personal preference really. We need an artist here.
Feel free to play with it and revamp the layout completely, if needed.

**Comment by tryggvigy** [comment]
Here is the Figma file I created for the original "design" of the landing page. https://www.figma.com/file/kpT1pGxzqlzCFRYaWyPMSw/COVID-19-Scenarios?node-id=0%3A1

Feel free to fork it and iterate. @realdy I like the colors, top bar and button style you have going on in this iteration.

@ivan-aksamentov I had a lot of problems with the svg wave. Like you already noticed it loads slow. It also adds quite a bit of complexity to the CSS because surrounding content has to adjust for it (the wave has to be absolutely position and change height to keep its aspect ratio on smaller screens). Another issue with the current design is that on some screen combinations the video/image can simply not be very big if it is positioned in the right side of the header.

I would suggest

- Removing svg wave in favor of a flat edge
- Move img/video below the header where it can get as much space as it needs.

**Comment by ivan-aksamentov** [comment]
Landing age is about to be removed
