### ISSUE TITLE
Form validation no longer works

### ISSUE THREAD

**Issue by ivan-aksamentov** [neherlab/covid19_scenarios#475]
# 🐛 Bug Report

Form validation no longer works. It has to be fixed ASAP.
There are no validation errors shown. Invalid values (for example negative) are silently accepted and passed to the algorithm.

## How to reproduce

Steps to reproduce the issue:

 1. Open the application in a browser
 2.
 3.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Browser          |
| Operating System |
|                  |

## Related

 -

**Comment by abrie** [comment]
Looks like the cause is missing validation parameters. For example, FormSpinBox validates according to min/max fields but in many cases none are specified:
      
https://github.com/neherlab/covid19_scenarios/blob/ae38b98612a7c9042b8ef5d6a771182b7599596c/src/components/Main/Scenario/ScenarioCardPopulation.tsx#L43-L50

**Comment by ivan-aksamentov** [comment]
@abrie This is not the validation we need. I mean this validation through Formik:
https://github.com/neherlab/covid19_scenarios/blob/master/src/components/Main/validation/schema.ts

**Comment by ivan-aksamentov** [comment]
It can be done with JSON schema-generated validators too I think. But it will require to figure out how to produce decent error messages.
