### ISSUE TITLE
Overlapping Interventions add up

### ISSUE THREAD

**Issue by ineiti** [neherlab/covid19_scenarios#605]
# 🐛 Bug Report

When two overlapping interventions are defined, the mitigations are added and the model behaves way too optimistic.

## How to reproduce

The standard mitigation for the USA has an Intervention for 40% starting March 20th, and another one for 60% starting March 25th. But if you look at the curves, they drop much faster than if you stop intervention #1 on March 24th.

## 😯 Current Behavior

Interventions add up.

## 🤔 Expected Behavior

When a second Intervention overlaps with the first one, the first one should stop being applied.

## 💁 Possible Solution

Automatically adjust the dates of Intervention #1 if Intervention #2 would overlap.

**Comment by noleti** [comment]
The mitigations are supposed to represent independent measures (i.e., school closure, social distancing, etc), which provide an individual mitigation factor. This is why the mitigations interact with each other (by design). They don't exactly add up (not like 40%+60%=100) but are multiplied: (1-0.4)*(1-0.6)= 0.24.  I agree that his could be stated more explicitly on the page or in the FAQ. Please also note that the default values are not based on true data, just something that is automatically initiated for you to modify.

**Comment by ineiti** [comment]
OK, now makes more sense. Thanks!
