### ISSUE TITLE
Backend-side work?

### ISSUE THREAD

**Issue by kibertoad** [neherlab/covid19_scenarios#66]
I'm a Node.js developer and I'd like to help, however, I'm not really proficient with React. If there is any non-React work that I could help with (either server-side or business logic isolated from React rendering), I would be most happy to contribute.

**Comment by ivan-aksamentov** [comment]
Hi @kibertoad , we currently don't have a backend other than a small lambda for securoty headers.

From the top of my head, in the non-UI code is in the `src/algorithms` directory. It contains te algorithm(s) and it can use some love. We are in desperate need of tests:
https://github.com/neherlab/covid19_scenarios/issues/19
In order to test the algorithm one needs to understand it and to split the internals into smaller functions. The most important thing thou is to not make worse in terms of results correctness and numeric accuracy.

We are thinking about backend, in order to store the scenarios and the results and maybe performing some heavier computing. Users then should be able to register, make runs and save results and share these results with other users.

We will organize the chat soon and I think it can be discussed in more details there. Feel free to take a look at the code meanwhile. If you have active proposals, that would also be fantastic!

**Comment by kibertoad** [comment]
@ivan-aksamentov Gotcha. I'll try to add some tests, and after those are in place, refactorings could be considered. Thanks!

**Comment by kibertoad** [comment]
@ivan-aksamentov Could you take a look https://github.com/neherlab/covid19_scenarios/pull/75 ? This lies a bit of groundwork for other work to be done, if this is right approach and direction, I can carry on from there.

**Comment by nonotest** [comment]
> Hi @kibertoad , we currently don't have a backend other than a small Lambda@Edge for security headers :)
> 
> From the top of my head, of you cannot digest React :), the non-UI code is in the `src/algorithms` directory. It contains tte algorithm(s) and it can use some love. We are in desperate need of tests:
> #19
> 
> In order to test the algorithm one needs to be able to understand it and to split the internals into smaller functions. Nick (@NNol) and Richard (@rneher) will provide any help in terms of explaining the science. The most important thing though is to not make things worse in terms of results correctness and numeric accuracy.
> 
> We are thinking about backend, in order to store the scenarios and the results and maybe performing some heavier computing. Users then should be able to register, make runs and save results and share these results with other users.
> 
> We will organize the chat soon and I think it can be discussed in more details there. Feel free to take a look at the code meanwhile. If you have active proposals, that would also be fantastic!

we could start by adding a few endpoints that return the current json files (population.json etc) for the web app to consume. When there is a clear path for the data sources we can load and transform the data dynamically from the backend instead of using the static json files. 

Happy to help with this as well

**Comment by rneher** [comment]
We are currently quite happy with the front-end only solution. We might revisit this at some point.
